---
title: "Text Mining The Office Transcripts"
author: "Soham"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


What are the top20 words used in The Office

```{r}
library(schrute)
library(dplyr)
library(tidyr)
library(tidytext)
library(ggplot2)


office = schrute::theoffice


word_counts <- office %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)%>%
  filter(!word %in% tolower(character))%>%
  count(word, sort = TRUE)%>%
  head(20)%>%
  mutate(word = reorder(word, n))



# Create a diverging color scale
color_scale <- scale_fill_viridis_c(option = "plasma", direction = -1,guide = "none")

# Plot the horizontal bar plot with a diverging color scale
ggplot(word_counts, aes(x = n, y = word, fill = n)) +
  geom_col() +
  labs(x = "Word Frequency", y = NULL, title = "Top 20 Words in The Office") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 8)) +
  color_scale

```
```{r}

maichael_dwight = office%>%
                  filter(character %in% c("Michael", "Dwight"))%>%
                  unnest_tokens(word, text) %>%
                  anti_join(stop_words)%>%
                  group_by(character)%>%
                  count(word, sort = TRUE)%>%
                 ungroup()

maichael_dwight %>%
          group_by(character)%>%
          top_n(15)%>%
          ungroup%>%
          mutate(character = as.factor(character),
                 word = reorder_within(word, n, character))%>%
           ggplot(aes(word, n, fill = character)) +
    geom_col(show.legend = FALSE) +
    facet_wrap(~character, scales = "free_y") +
    coord_flip() +
    scale_x_reordered() +
    scale_y_continuous(expand = c(0,0)) +
    labs(y = "Number of words",
         x = NULL,
         title = "What were the top words used by Michael and Dwight?",
        )

maichael_dwight
```
```{r}
```


